services:
  nlp_app:
    build: .
    volumes:
      - .:/app
      - ./hf_cache:/root/.cache/huggingface # Cache for Hugging Face models (for note downloading models every time)
      - ./chroma_db:/app/chroma_db
    env_file:
      - .env
    ports:
      - "8501:8501" # Streamlit default port
      - "8888:8888" # JupyterLab default port
      - "5000:5000"    # MLflow (opsiyonel)
    command: jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token=''
    tty: true
    stdin_open: true